### ISSUE TITLE
Adding a Background Image and Removing Margins with CSS

### ISSUE THREAD

**Issue by mharoot** [mharoot/VisualComposer#1]
# Adding a Background Image and Removing Margins with CSS
Consider the following use case:
### The Design of the Barber Shop on Desktop
We would like to have a background image similar to this mockup [barber-shop-website](https://avada.theme-fusion.com/barber-shop/):
![Screen Shot 2019-07-26 at 1 41 42 PM](https://user-images.githubusercontent.com/24758613/61980378-780e9200-afab-11e9-9381-bf2970c00852.png)
### The Design of the Barber Shop on Iphone 5/SE
Notice the background image holds its width and the full height of the device.
![Screen Shot 2019-07-26 at 1 50 47 PM](https://user-images.githubusercontent.com/24758613/61980751-7db8a780-afac-11e9-9adc-1f24313b8e6e.png)

### The Design of Our Site on Desktop
It is problematic for us to have the whitespace at the top. 
![Screen Shot 2019-07-26 at 1 39 14 PM](https://user-images.githubusercontent.com/24758613/61980187-d38c5000-afaa-11e9-9e7d-447f67e1819d.png)
We need to remove the margin style responsible for causing this and we can do so quickly my customize the pages css.

# CSS Solution

### The Snippet
```css
.entry .entry-content > *, .entry .entry-summary > * {
    margin: 0px;
}
```

**Comment by mharoot** [comment]
# How to Add a Background Image With Visual Composer
### 1. Hover over pages and select add new page with visual composer:
![Screen Shot 2019-07-26 at 2 03 19 PM](https://user-images.githubusercontent.com/24758613/61981655-1a7c4480-afaf-11e9-8ce3-19d3f1692f59.png)
----
### 2. Type in a `Page title` and `Page slug` for the url and select the `Add New Element` button:
![Screen Shot 2019-07-26 at 2 07 56 PM](https://user-images.githubusercontent.com/24758613/61981633-0afcfb80-afaf-11e9-9c18-51bceb6bd4d3.png)
### 3. Select Row:
![Screen Shot 2019-07-26 at 2 12 51 PM](https://user-images.githubusercontent.com/24758613/61981782-8068cc00-afaf-11e9-94e3-e97a2fd01803.png)
### 4. Select Stretched Row and Column Setting:
![Screen Shot 2019-07-26 at 2 14 14 PM](https://user-images.githubusercontent.com/24758613/61981852-bd34c300-afaf-11e9-9407-a7729f7806fa.png)
### 5. Scroll down to Full Height and turn it on so that so you can set the row to be full screen height, you should see additional options pop up below:
![Screen Shot 2019-07-26 at 2 16 56 PM](https://user-images.githubusercontent.com/24758613/61982102-89a66880-afb0-11e9-9508-0a900e9ecb54.png)
### 6. Scroll Down to Images and Select Add Image:
![Screen Shot 2019-07-26 at 2 23 04 PM](https://user-images.githubusercontent.com/24758613/61982243-f0c41d00-afb0-11e9-985b-d1860a84f389.png)
### 7. Upload an image, you may need to refresh the page in order the select the image.  Select the image and press the `Add Image` Button:
![Screen Shot 2019-07-26 at 2 24 14 PM](https://user-images.githubusercontent.com/24758613/61982309-37197c00-afb1-11e9-8d64-8314e46136e4.png)
### 8. Assure `Background Style` is `Cover` and Selecting Any of the center Icons should position it in the center and would not make any difference if it's in the top middle or bottom.
![Screen Shot 2019-07-26 at 2 28 02 PM](https://user-images.githubusercontent.com/24758613/61982463-a68f6b80-afb1-11e9-88b9-408c5f7caf9c.png)
### 9. Once you are done you need to publish it and close the page
![Screen Shot 2019-07-26 at 2 30 38 PM](https://user-images.githubusercontent.com/24758613/61982565-0259f480-afb2-11e9-9f9c-da8f5c3d2378.png)
### 10. We can now navigate back to our page using the slug `issue1` after the `host name`: `http://localhost:8888/visual_composer_demo/issue1/`
![Screen Shot 2019-07-26 at 2 32 01 PM](https://user-images.githubusercontent.com/24758613/61982605-274e6780-afb2-11e9-8527-f0551d869d2b.png)

**Comment by mharoot** [comment]
# How to Find the CSS to style Using Google Chrome Inspector
### 1. Right click, inspect in chrome, hover over the body html element code snippet and click to view the CSS styling:
![Screen Shot 2019-07-26 at 2 44 18 PM](https://user-images.githubusercontent.com/24758613/61983104-e48d8f00-afb3-11e9-8f5e-bccc10ced2bf.png)

### 2. Work your way down each element, clicking them one by one, until you find what is causing the white space at the top:
![Screen Shot 2019-07-26 at 2 46 47 PM](https://user-images.githubusercontent.com/24758613/61983175-39c9a080-afb4-11e9-8dd8-b28507d3f34c.png)

### 3. We can copy the culprit css straight from chrome inspector and start modifying the css for it: 
![Screen Shot 2019-07-26 at 2 48 45 PM](https://user-images.githubusercontent.com/24758613/61983286-a2188200-afb4-11e9-9a55-ec247747d701.png)

### 4. Start modifying the css code directly from chrome inspector
```css
.entry .entry-content, .entry .entry-summary {
    max-width: 80%;
    margin: 0 10%;
    padding: 0 60px;
}

### 5. If you notice after playing around with the settings that the whitespace is not being removed then you must look for another source of where it is coming from. In my case this did not resolve my issue.
```css
.entry .entry-content, .entry .entry-summary {
    margin: 0;
}
```

### 6.  Keep searching by clicking each element until you find the real culprit:
![Screen Shot 2019-07-26 at 3 07 09 PM](https://user-images.githubusercontent.com/24758613/61983927-105e4400-afb7-11e9-9446-da35f6dfa18c.png)

### 7. Solution found my setting this in chrome Inspector.
```css
.entry .entry-content > *, .entry .entry-summary > * {
    margin: 0px;
}
```
